import os

with open("wikilocation.c", "w+") as f:
    f.write(
        f"""// DO NOT CHANGE. FILE AUTO-GENERATED BY meta.py

// Output is guaranteed to be written at this location after Python call
static char *OUTPUT_FILE =
    "{os.getcwd()}/.local.output.txt";

static char *PYTHON_SCRIPT_PATH =
    "{os.getcwd()}/wikipedia.py";
"""
    )
